const fs = require('fs');

// Completely rewrite codemagic.yaml from scratch with ALL fixes baked in
const yaml = `# Auto-generated by RRAASI Vibe Platform
# DO NOT EDIT — regenerated before every build

workflows:
  android-apk:
    name: Android APK Build (Dev)
    max_build_duration: 90
    working_directory: .
    environment:
      node: 20
      java: 17
    scripts:
      - name: Set API backend URL
        script: |
          echo BACKEND_URL=${BACKEND_URL:-https://api-metal-connect.dev.rraasi.com} >> .env
          echo API_BASE_URL=${BACKEND_URL:-https://api-metal-connect.dev.rraasi.com} >> .env
          echo EXPO_PUBLIC_API_URL=${BACKEND_URL:-https://api-metal-connect.dev.rraasi.com} >> .env
      - name: Install dependencies
        script: npm install --legacy-peer-deps
      - name: Expo Prebuild
        script: npx expo prebuild --platform android --clean --non-interactive
      - name: Patch Android Build
        script: |
          cd android
          # Force Gradle 8.10.2
          sed -i.bak -e 's/gradle-.*-all.zip/gradle-8.10.2-all.zip/' gradle/wrapper/gradle-wrapper.properties
          sed -i.bak -e 's/gradle-.*-bin.zip/gradle-8.10.2-bin.zip/' gradle/wrapper/gradle-wrapper.properties
          # Remove incompatible React Native 0.76 properties from app/build.gradle
          sed -i.bak -e '/hermesCommand = /d' app/build.gradle
          sed -i.bak -e '/enableBundleCompression = /d' app/build.gradle
          # Force kotlinVersion in gradle.properties
          echo '' >> gradle.properties
          echo 'kotlinVersion=2.1.20' >> gradle.properties
          # Use node to safely patch settings.gradle and build.gradle
          node ../patch_android.js
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease -x lint
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
    publishing:
      scripts:
        - name: Notify build complete
          script: |
            curl -s -X POST \\
              -H Content-Type: application/json \\
              -H x-webhook-secret: ad_codemagic_webhook_2025 \\
              -d {\\\buildId\\\: \\\$CM_BUILD_ID\\\, \\\status\\\: \\\$CM_BUILD_STEP_STATUS\\\, \\\appId\\\: \\\$CM_PROJECT_ID\\\} \\
              https://ad.rraasi.com/api/webhooks/codemagic || true

  android-aab:
    name: Android AAB Build (Production / Play Store)
    max_build_duration: 90
    working_directory: .
    environment:
      node: 20
      java: 17
    scripts:
      - name: Set API backend URL
        script: |
          echo BACKEND_URL=${BACKEND_URL:-https://api-metal-connect.dev.rraasi.com} >> .env
          echo API_BASE_URL=${BACKEND_URL:-https://api-metal-connect.dev.rraasi.com} >> .env
          echo EXPO_PUBLIC_API_URL=${BACKEND_URL:-https://api-metal-connect.dev.rraasi.com} >> .env
      - name: Install dependencies
        script: npm install --legacy-peer-deps
      - name: Expo Prebuild
        script: npx expo prebuild --platform android --clean --non-interactive
      - name: Build AAB
        script: |
          cd android
          ./gradlew bundleRelease -x lint
    artifacts:
      - android/app/build/outputs/bundle/release/app-release.aab
    publishing:
      scripts:
        - name: Notify build complete
          script: |
            curl -s -X POST \\
              -H Content-Type: application/json \\
              -H x-webhook-secret: ad_codemagic_webhook_2025 \\
              -d {\\\buildId\\\: \\\$CM_BUILD_ID\\\, \\\status\\\: \\\$CM_BUILD_STEP_STATUS\\\, \\\appId\\\: \\\$CM_PROJECT_ID\\\} \\
              https://ad.rraasi.com/api/webhooks/codemagic || true
`;

fs.writeFileSync('codemagic.yaml', yaml);
console.log('Rewrote codemagic.yaml');

// Now write the patch_android.js script that does ALL patching safely
const patchScript = `const fs = require('fs');
const path = require('path');

// 1. Patch settings.gradle - inject resolutionStrategy into existing pluginManagement block
let settings = fs.readFileSync('android/settings.gradle', 'utf8');
const resStrategy = \`
  resolutionStrategy {
    eachPlugin {
      if (requested.id.id == org.jetbrains.kotlin.android) {
        useVersion(2.1.20)
      }
      if (requested.id.id == org.jetbrains.kotlin.jvm) {
        useVersion(2.1.20)
      }
    }
  }
\`;
settings = settings.replace('pluginManagement {', 'pluginManagement {' + resStrategy);
fs.writeFileSync('android/settings.gradle', settings);
console.log('Patched settings.gradle with pluginManagement resolutionStrategy');

// 2. Patch build.gradle - force ALL kotlin deps to 2.1.20 across all subprojects
let buildGradle = fs.readFileSync('android/build.gradle', 'utf8');
const forceBlock = \`

// Force all Kotlin dependencies to 2.1.20 to fix Expo SDK 56 + RN 0.76 compatibility
subprojects {
    afterEvaluate {
        configurations.configureEach {
            resolutionStrategy.eachDependency { details ->
                if (details.requested.group == 'org.jetbrains.kotlin') {
                    details.useVersion('2.1.20')
                }
                if (details.requested.group == 'io.github.lukmccall.pika' && details.requested.name == 'pika-compiler') {
                    details.useVersion('0.3.2-2.1.20')
                }
            }
        }
    }
}
\`;
buildGradle += forceBlock;
fs.writeFileSync('android/build.gradle', buildGradle);
console.log('Patched build.gradle with global Kotlin version override');
`;

fs.writeFileSync('patch_android.js', patchScript);
console.log('Created patch_android.js');
